name: "Export Monthly Data"
description: "Given a game and a month, this action will export the month's data for that game."
inputs:
  month_year: # month and year
    description: "The month and year to export."
    required: true
    default: ''
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  ssh_host:
    description: "The server hosting the OGD database."
    required: true
    default: '127.0.0.1'
  vpn_user:
    description: "Username for logging in to the VPN."
    required: true
    default: 'user placeholder'
  vpn_pass:
    description: "Password for logging in to the VPN."
    required: true
    default: 'password placeholder'
  sql_user:
    description: "Username for logging in to the SQL database."
    required: true
    default: 'user placeholder'
  sql_pass:
    description: "Password for logging in to the SQL database."
    required: true
    default: 'password placeholder'
runs:
  using: "composite"
  steps:
    - name: Get export month
      run: |
        MONTH=$(date -d "$(date +%Y-%m-01) -1 month" +'%m')
        YEAR=$(date -d "$(date +%Y-%m-01) -1 month" +'%Y')
        MONTH_YEAR=$MONTH/$YEAR
        echo exporting $MONTH_YEAR
      shell: bash
    # Runs a single command using the runners shell
    # - name: Ensure we have mysql client installed.
    #   run: sudo apt-get install mysql-client
      # shell: bash
    - name: Get correct Python
      run: |
        sudo apt-get install python3.8
        sudo apt-get install python3.8-dev
      shell: bash
    - name: Set up local bin in path # there is a warning about this in pip output, so we'll do this and see if that makes things better.
      run: export PATH=/home/runner/.local/bin:$PATH
      shell: bash
    - name: Set up Python libraries
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setuptools
        python3.8 -m pip install wheel
        python3.8 -m pip install -r requirements.txt
      shell: bash
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Set up code
      run: cp config.py.template config.py 
      shell: bash
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{inputs.ssh_host}}/g' config.py
      shell: bash
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{inputs.vpn_user}}/g' config.py
      shell: bash
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{inputs.vpn_pass}}/g' config.py
      shell: bash
    - name: Set SQL username
      run: sed -i 's/username/${{inputs.sql_user}}/g' config.py
      shell: bash
    - name: Set SQL password
      run: sed -i 's/password/${{inputs.sql_pass}}/g' config.py
      shell: bash
    - name: Execute data export
      run: |
        python3.8 main.py readme ${{ inputs.game }}
        python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021
      shell: bash
        # python3.8 main.py export ${{ inputs.game }} $MONTH_YEAR --monthly
    # - name: Test ssh with just username and password.
    #   uses: garygrossgarten/github-action-ssh@release
    #   with:
    #     command: pwd & ls
    #     host: ${{secrets.FILE_HOST}}
    #     username: ${{secrets.FILE_USER}}
    #     privateKey: ${{secrets.FILE_DEPLOY_KEY}}