name: "Export Monthly Data"
description: "Given a game, this action will export last month's data for that game."
inputs:
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  month_year:
   description: "The month and year to export."
   required: true
   default: '01/2021'
  vpn_user:
    description: "Username for logging in to the VPN."
    required: true
    default: 'user placeholder'
  vpn_pass:
    description: "Password for logging in to the VPN."
    required: true
    default: 'password placeholder'
  sql_host:
    description: "The server hosting the OGD database."
    required: true
    default: '127.0.0.1'
  sql_user:
    description: "Username for logging in to the SQL database."
    required: true
    default: 'user placeholder'
  sql_pass:
    description: "Password for logging in to the SQL database."
    required: true
    default: 'password placeholder'
runs:
  using: "composite"
  steps:
    - name: Set up local bin in path # there is a warning about this in pip output, so we'll do this and see if that makes things better.
      run: export PATH=/home/runner/.local/bin:$PATH
      shell: bash
    - name: Set up Python libraries
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setuptools --quiet
        python3.8 -m pip install wheel --quiet
        python3.8 -m pip install -r requirements.txt --quiet
      shell: bash
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Set up code
      run: cp config.py.template config.py 
      shell: bash
    - name: Set table to the 2019-2020 one
      run: sed -i 's/logger/logger2020/g' config.py
      shell: bash
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{inputs.sql_host}}/g' config.py
      shell: bash
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{inputs.vpn_user}}/g' config.py
      shell: bash
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{inputs.vpn_pass}}/g' config.py
      shell: bash
    - name: Set SQL username
      run: sed -i 's/username/${{inputs.sql_user}}/g' config.py
      shell: bash
    - name: Set SQL password
      run: sed -i 's/password/${{inputs.sql_pass}}/g' config.py
      shell: bash
    - name: Execute data export
      run: python3.8 main.py export ${{ inputs.game }} ${{ inputs.month_year }} --monthly
      shell: bash
      # python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021