name: "Export Monthly Data"
author: Luke Swanson
description: "Given a game, this action will export last month's data for that game."
branding:
  icon: 'calendar'
  color: 'purple'
inputs:
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  month_year:
   description: "The month and year to export."
   required: true
   default: '01/2021'
  vpn_user:
    description: "Username for logging in to the VPN."
    required: true
    default: 'user placeholder'
  vpn_pass:
    description: "Password for logging in to the VPN."
    required: true
    default: 'password placeholder'
  sql_host:
    description: "The server hosting the OGD database."
    required: true
    default: '127.0.0.1'
  sql_user:
    description: "Username for logging in to the SQL database."
    required: true
    default: 'user placeholder'
  sql_pass:
    description: "Password for logging in to the SQL database."
    required: true
    default: 'password placeholder'
  sql_db:
    description: "Which SQL database to use"
    required: true
    default: "logger"
  log_level:
    description: "Logging level to use for export process"
    required: true
    default: "INFO"
  slice_size:
    description: "Number of sessions to process at a time"
    required: true
    default: 1000
runs:
  using: "composite"
  steps:
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Set up config
      run: cp config/config.py.template config/config.py 
      shell: bash
    # - name: Set table to the 2019-2020 one
    #   run: sed -i 's/logger/logger2020/g' config.py
    #   shell: bash
    - name: Set Logger level
      run: sed -i 's/INFO/${{inputs.log_level}}/g' config/config.py
      shell: bash
    - name: Set Slice Size
      run: sed -i 's/"BATCH_SIZE":1000/"BATCH_SIZE":${{inputs.slice_size}}/g' config/config.py
      shell: bash
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{inputs.sql_host}}/g' config/config.py
      shell: bash
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{inputs.vpn_user}}/g' config/config.py
      shell: bash
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{inputs.vpn_pass}}/g' config/config.py
      shell: bash
    - name: Set SQL username
      run: sed -i 's/username/${{inputs.sql_user}}/g' config/config.py
      shell: bash
    - name: Set SQL password
      run: sed -i 's/password/${{inputs.sql_pass}}/g' config/config.py
      shell: bash
    - name: Set SQL database
      run: sed -i 's/logger/${{inputs.sql_db}}/g' config/config.py
      shell: bash
    - name: Set Aqualab config
      if: ${{ inputs.game == 'AQUALAB' }}
      run: sed -i 's/aqualab_project_id.dataset_id/aqualab-57f88.analytics_271167280/g' config/config.py
      shell: bash
    - name: Execute data export
      run: python3.8 main.py export ${{ inputs.game }} ${{ inputs.month_year }} --monthly
      shell: bash
      # python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021
