name: "Export Range of Data"
description: "Given a game and a date range, this action will export the range's data for that game."
inputs:
  start_date: # month and year
    description: "The month, day, and year to start export range."
    required: true
    default: ''
  end_date: # month and year
    description: "The month, day, and year to end export range."
    required: true
    default: ''
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  vpn_user:
    description: "Username for logging in to the VPN."
    required: true
    default: 'user placeholder'
  vpn_pass:
    description: "Password for logging in to the VPN."
    required: true
    default: 'password placeholder'
  sql_host:
    description: "The server hosting the OGD database."
    required: true
    default: '127.0.0.1'
  sql_user:
    description: "Username for logging in to the SQL database."
    required: true
    default: 'user placeholder'
  sql_pass:
    description: "Password for logging in to the SQL database."
    required: true
    default: 'password placeholder'
  log_level:
    description: "Logging level to use for export process"
    required: true
    default: "DEBUG"
runs:
  using: "composite"
  steps:
    - name: Get yesterday, for export
      run: |
        YESTERDAY=$(date -d "$(date +%Y-%m-%d) -1 day" +'%m/%d/%Y')
        echo "YESTERDAY=" $YESTERDAY >> $GITHUB_ENV
      shell: bash
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Set up code
      run: cp config/config.py.template config/config.py 
      shell: bash
    - name: Set Logger level
      run: sed -i 's/INFO/${{inputs.log_level}}/g' config/config.py
      shell: bash
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{inputs.sql_host}}/g' config/config.py
      shell: bash
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{inputs.vpn_user}}/g' config/config.py
      shell: bash
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{inputs.vpn_pass}}/g' config/config.py
      shell: bash
    - name: Set SQL username
      run: sed -i 's/username/${{inputs.sql_user}}/g' config/config.py
      shell: bash
    - name: Set SQL password
      run: sed -i 's/password/${{inputs.sql_pass}}/g' config/config.py
      shell: bash
    - name: Execute data export
      run: python3.8 main.py export ${{ inputs.game }} ${{env.YESTERDAY}} ${{env.YESTERDAY}}
      shell: bash
      # python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021