name: "Export Range of Data"
author: Luke Swanson
description: "Given a game and a date range, this action will export the range's data for that game."
branding:
  icon: 'arrow-left'
  color: 'orange'
inputs:
  start_date: # month and year
    description: "The month, day, and year to start export range."
    required: true
    default: ''
  end_date: # month and year
    description: "The month, day, and year to end export range."
    required: true
    default: ''
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
runs:
  using: "composite"
  steps:
    - name: Get yesterday, for export
      run: |
        YESTERDAY=$(date -d "$(date +%Y-%m-%d) -1 day" +'%m/%d/%Y')
        echo "YESTERDAY=" $YESTERDAY >> $GITHUB_ENV
      shell: bash
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Execute data export
      run: python3.8 main.py export ${{ inputs.game }} ${{env.YESTERDAY}} ${{env.YESTERDAY}}
      shell: bash
      # python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021
