name: Aqualab BigQuery Test
on:
  push:
    paths:
    - 'games/AQUALAB/**'
    - '.github/workflows/aqualab.yml'
  workflow_dispatch:
jobs:
  test_connect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies
    # - name: Use gcloud CLI
    #   run: |
    #     gcloud config set project aqualab-57f88
    #     bq query --use_legacy_sql=false \
    #     'SELECT
    #       event_name
    #     FROM
    #       `aqualab-57f88.analytics_271167280.events_20210915`'
    - name: Do Export of last month's data
      uses: ./.github/actions/export_last_month
      with:
        game: AQUALAB
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_host: ${{secrets.SQL_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        log_level: "INFO"
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./*.log
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/AQUALAB/*.zip
