# Workflow to run monthly exports of data.
name: Automated Monthly Exports
on:
  schedule:
    - cron: '1 0 2 * *'
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
jobs:
  export_data:
    name: Export All Games
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # game: [AQUALAB, BACTERIA, BALLOON, CRYSTAL, CYCLE_CARBON, CYCLE_NITROGEN, CYCLE_WATER, EARTHQUAKE, JOWILDER, LAKELAND, MAGNET, STEMPORTS, WAVES, WIND]
        game: [BACTERIA]

  # bacteria:
  #   name: Export Bacteria
  #   runs-on: ubuntu-latest
    # Steps to set up for and execute an export
    steps:
    - name: Get OpenConnect
      run: sudo add-apt-repository ppa:phusen/openconnect && sudo apt-get update && sudo apt-get install openconnect
    - uses: actions/checkout@v2
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &
    - name: Do Export
      uses: ./.github/actions/export_month
      with:
        game: ${{matrix.game}}
        ssh_host: ${{secrets.SSH_HOST}}
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
    - name: Upload files to opengamedata via scp
      run: |
        mkdir -p ~/.ssh
        echo '${{secrets.FILE_DEPLOY_KEY}}' >> ./key.txt
        chmod 600 ./key.txt
        scp -o StrictHostKeyChecking=no -i ./key.txt ./data/BACTERIA/* ${{ secrets.VPN_USER }}@${{ secrets.FILE_HOST }}:/var/www/opengamedata/data/BACTERIA/