# Workflow to run monthly exports of data.
name: Automated Monthly Exports
on:
  schedule:
    - cron: '1 0 2 * *'
  workflow_dispatch # Allow manual trigger of this workflow from the Actions tab
jobs:
  # This workflow contains a single job called "monthly_export"
  bacteria:
    # The type of runner that the job will run on
    name: Export Earthquake
    runs-on: ubuntu-latest
    # Steps to set up for and execute an export
    steps:
    - uses: actions/checkout@v2
    - name: Do Export
      uses: ./.github/actions/export_month
      with:
        game: 'BACTERIA'
        ssh_host: ${{secrets.SSH_HOST}}
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
    - name: Upload files to opengamedata via rsync
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -vrc
        path: data/*
        remote_path: /var/www/opengamedata/data/
        remote_host: ${{ secrets.FILE_HOST }}
        remote_user: ${{ secrets.FILE_USER }}
        remote_key: ${{ secrets.FILE_DEPLOY_KEY }}

  earthquake:
    # The type of runner that the job will run on
    name: Export Earthquake
    runs-on: ubuntu-latest
    # Steps to set up for and execute an export
    steps:
    - uses: actions/checkout@v2
    - name: Do Export
      uses: ./.github/actions/export_month
      with:
        game: 'EARTHQUAKE'
        ssh_host: ${{secrets.SSH_HOST}}
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
    - name: Upload files to opengamedata via rsync
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -vrc
        path: data/*
        remote_path: /var/www/opengamedata/data/
        remote_host: ${{ secrets.FILE_HOST }}
        remote_user: ${{ secrets.FILE_USER }}
        remote_key: ${{ secrets.FILE_DEPLOY_KEY }}