name: Mashopolis Exporter CI Test
on:
  push:
    paths:
    - 'games/MASHOPOLIS/**'
    - '.github/workflows/mashopolis.yml'
  workflow_dispatch:
jobs:
  Mashopolis_CI:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.BQ_MASHOPOLIS_PROJECT_ID }}
        service_account_key: ${{ secrets.BQ_MASHOPOLIS_JSON }}
        export_default_credentials: true
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_host: ${{secrets.SQL_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        log_level: "DEBUG"
    - name: Set up Schema File
      uses: ./.github/actions/OGD_schema
      with:
        game: "MASHOPOLIS"
    - name: Do Export of last week's data
      uses: ./.github/actions/export_last_week
      with:
        game: MASHOPOLIS
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./*.log
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/MASHOPOLIS/*.zip
