name: Aqualab Readme Update Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}

on:
  push:
    paths:
    - 'src/ogd/games/AQUALAB/schemas/AQUALAB.json.template'
    - '.github/workflows/README_aqualab.yml'
  workflow_dispatch:

jobs:
  ci_export:
    name: Update Aqualab README.md
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies

  # 2. Configure cloud & local environments
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        ssh_host: ${{vars.FD_STORE_HOST}}
        ssh_user: ${{secrets.VPN_USER}}
        ssh_pass: ${{secrets.VPN_PASS}}
    - name: Set up Schema File
      uses: ./.github/actions/OGD_schema
      with:
        game: "AQUALAB"

  # 3. Generate README
    - name: Create README file
      run: python main.py readme AQUALAB --destination src/ogd/games

  # 4. Cleanup & complete
    - name: Upload data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: AQUALAB_readme
        path: ./src/ogd/games/AQUALAB/README.md
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log_data
        path: ./*.log
