
# Workflow to run monthly exports of data.
# All games, and months, for copy-paste:
# game: ['AQUALAB', 'BACTERIA', 'BALLOON', 'CRYSTAL', 'CYCLE_CARBON', 'CYCLE_NITROGEN', 'CYCLE_WATER', 'EARTHQUAKE', 'JOWILDER', 'LAKELAND', 'MAGNET', 'STEMPORTS', 'WAVES', 'WIND']
# month-year: ['03/2019', '04/2019', '05/2019', '06/2019', '07/2019', '08/2019', '09/2019', '10/2019', '11/2019', '12/2019', '01/2020', '02/2020', '03/2020', '04/2020', '05/2020', '06/2020', '07/2020', '08/2020', '09/2020']
name: Update Aqualab Readme
on:
  push:
    paths:
    - 'src/ogd/games/AQUALAB/schemas/AQUALAB.json.template'
  workflow_dispatch:

jobs:
  Update_Readme:
    name: Update README.md

    # Steps to set up for and execute an export
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      # A bunch of copy-paste crap to set up google cloud for any given game.
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        ssh_host: ${{vars.FD_STORE_HOST}}
        ssh_user: ${{secrets.VPN_USER}}
        ssh_pass: ${{secrets.VPN_PASS}}
    - name: Set up Schema File
      uses: ./.github/actions/OGD_schema
      with:
        game: "AQUALAB"
    - name: Create README file
      run: python main.py readme AQUALAB --destination src/ogd/games
    - name: Upload data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: AQUALAB_readme
        path: ./src/ogd/games/AQUALAB/README.md
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log_data
        path: ./*.log
