name: All You Can ET Readme Update Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}

on:
  push:
    paths:
    - 'src/ogd/games/ALL_YOU_CAN_ET/schemas/ALL_YOU_CAN_ET.json.template'
    - '.github/workflows/README_all_you_can_et.yml'
  workflow_dispatch:

jobs:
  ci_export:
    name: Update All You Can ET README.md
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies

  # 2. Configure cloud & local environments
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        ssh_host: ${{vars.FD_STORE_HOST}}
        ssh_user: ${{secrets.VPN_USER}}
        ssh_pass: ${{secrets.VPN_PASS}}
    - name: Set up Schema File
      uses: ./.github/actions/OGD_schema
      with:
        game: "ALL_YOU_CAN_ET"

  # 3. Generate README
    - name: Create README file
      run: python main.py readme ALL_YOU_CAN_ET --destination src/ogd/games
    - name: Commit README file
      run: |
        git config --global user.name 'fieldday-service'
          git config --global user.email 'fieldday@office365.wisc.edu'
          git commit -am "Update All You Can ET README"
          git push

  # 4. Cleanup & complete
    - name: Upload data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ALL_YOU_CAN_ET_readme
        path: ./src/ogd/games/ALL_YOU_CAN_ET/README.md
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log_data
        path: ./*.log
