# Workflow to test-run data when we modify CrystalExtractor.
name: Test running conditionals.
on:
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
    inputs:
      monthly:
        description: "The conditional"
        required: true
        default: false
jobs:
  test_export:
    name: Export Game
    runs-on: ubuntu-latest

    steps:
    - name: Do Export of Month
      if: ${{ github.event.inputs.monthly == 'true' }}
      run: echo Did it!
    - name: Do Export of Range
      if: ${{ github.event.inputs.monthly != 'true' }}
      run: echo Did not do it!